/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/game/hand": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fetch Hand */
        post: operations["fetch_hand_api_v1_game_hand_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/game/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Answer */
        post: operations["record_answer_api_v1_game_answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/game/hint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Hint */
        post: operations["request_hint_api_v1_game_hint_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/curriculum/grades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Grades
         * @description Return available grade names.
         */
        get: operations["get_grades_api_v1_curriculum_grades_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user_model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User Model */
        get: operations["get_user_model_api_v1_user_model_get"];
        put?: never;
        post?: never;
        /** Reset User Model */
        delete: operations["reset_user_model_api_v1_user_model_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Card */
        Card: {
            /** Card Id */
            card_id: string;
            /** Card Name */
            card_name: string;
            /** Card Power */
            card_power: number;
            /**
             * Card Type
             * @enum {string}
             */
            card_type: "attack" | "heal" | "shield";
            /** Attack Subtype */
            attack_subtype?: ("magic" | "bow" | "sword" | "axe") | null;
            /** Energy Cost */
            energy_cost: number;
            task: components["schemas"]["Task"];
        };
        /** DifficultyRecord */
        DifficultyRecord: {
            /** Topic */
            topic: string;
            /** Difficulty */
            difficulty: string;
            /**
             * Attempts
             * @default 0
             */
            attempts: number;
            /**
             * Hints
             * @default 0
             */
            hints: number;
            /**
             * Correct
             * @default 0
             */
            correct: number;
        };
        /** FetchHandRequest */
        FetchHandRequest: {
            /** Grade */
            grade: string;
        };
        /** FetchHandResponse */
        FetchHandResponse: {
            /** Hand */
            hand: components["schemas"]["Card"][];
        };
        /** GradesResponse */
        GradesResponse: {
            /** Grades */
            grades: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HintRequest */
        HintRequest: {
            /** Grade */
            grade: string;
            /** Topic */
            topic: string;
            /** Difficulty */
            difficulty: string;
            /** Question */
            question: string;
            /** Student Work */
            student_work?: components["schemas"]["Stroke"][] | null;
            /**
             * Canvas Width
             * @default 512
             */
            canvas_width: number;
            /**
             * Canvas Height
             * @default 512
             */
            canvas_height: number;
            /** Previous Hints */
            previous_hints?: string[];
            /** Previous Attempts */
            previous_attempts?: string[];
        };
        /** HintResponse */
        HintResponse: {
            /** Guiding Question */
            guiding_question: string;
        };
        /** Point */
        Point: {
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** RecordAnswerRequest */
        RecordAnswerRequest: {
            /** Topic */
            topic: string;
            /** Difficulty */
            difficulty: string;
            /** Correct */
            correct: boolean;
        };
        /** RecordAnswerResponse */
        RecordAnswerResponse: {
            /**
             * Ok
             * @default true
             */
            ok: boolean;
        };
        /** Stroke */
        Stroke: {
            /** Points */
            points?: components["schemas"]["Point"][];
            /** Timestamp Ms */
            timestamp_ms: number;
        };
        /** Task */
        Task: {
            /** Task Id */
            task_id: string;
            /** Question */
            question: string;
            /** Grade */
            grade: string;
            /** Topic */
            topic: string;
            /** Difficulty */
            difficulty: string;
            /** Expected Answer */
            expected_answer: string;
            /**
             * Answer Type
             * @default number
             * @enum {string}
             */
            answer_type: "number" | "fraction" | "text";
            /** Accepted Answers */
            accepted_answers?: string[];
        };
        /**
         * TopicRecord
         * @description Aggregated performance data for one topic within a session.
         */
        TopicRecord: {
            /** Topic */
            topic: string;
            /** Records */
            records: {
                [key: string]: components["schemas"]["DifficultyRecord"];
            };
        };
        /** UserModelResponse */
        UserModelResponse: {
            /** Topics */
            topics: components["schemas"]["TopicRecord"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    fetch_hand_api_v1_game_hand_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FetchHandRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FetchHandResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_answer_api_v1_game_answer_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordAnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordAnswerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_hint_api_v1_game_hint_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HintRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HintResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_grades_api_v1_curriculum_grades_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GradesResponse"];
                };
            };
        };
    };
    get_user_model_api_v1_user_model_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserModelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_user_model_api_v1_user_model_delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
