import json
from abc import ABC, abstractmethod
from uuid import uuid4

from backend.models.game import Task
from backend.models.assistant import HelpResponse
from backend.services.logger import log
from backend.services.llm.prompts import GUIDANCE_SYSTEM_PROMPT, TASK_SYSTEM_PROMPT, HAND_SELECTOR_SYSTEM_PROMPT


def _extract_json(text: str) -> dict:
    """Extract and parse the first complete JSON object from *text*."""
    start = text.find("{")
    end = text.rfind("}")
    if start == -1 or end == -1 or end < start:
        raise RuntimeError(f"No JSON object found in LLM response: {text!r}")
    try:
        return json.loads(text[start : end + 1])
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"Invalid JSON in LLM response: {exc}\nRaw: {text!r}") from exc


def build_guide_user_text(
    question: str,
    context: str,
    has_image: bool,
    profile_context: str = "",
) -> str:
    text = f"Curriculum context:\n{context}\n\nMath task the student is working on:\n{question}\n\n"
    if has_image:
        text += "The student has submitted handwritten work (see image). Please consider it.\n\n"
    if profile_context:
        text += f"{profile_context}\n\n"
    return text


def build_task_text(
    grade: str,
    topic: str,
    difficulty: str,
    curriculum_context: str = "",
    profile_context: str = "",
) -> str:
    text = f"Grade:\n{grade}\n\nTopic:\n{topic}\n\nDifficulty:\n{difficulty}\n\n"
    if curriculum_context:
        text += f"Curriculum context:\n{curriculum_context}\n\n"
    if profile_context:
        text += f"{profile_context}\n\n"
    return text


def build_hand_selector_text(topics: list[str], profile_context: str, hand_size: int) -> str:
    topic_list = "\n".join(f"- {t}" for t in topics)
    text = f"Available topics:\n{topic_list}\n\nNumber of card slots to fill: {hand_size}\n\n"
    if profile_context:
        text += f"{profile_context}\n\n"
    return text


def _parse_guidance(raw: str) -> str:
    """Extract ``guiding_question`` from a guidance JSON response."""
    data = _extract_json(raw)
    guiding_question = data.get("guiding_question", "")
    if not isinstance(guiding_question, str) or not guiding_question.strip():
        raise RuntimeError(f"Missing or empty 'guiding_question' in response: {raw!r}")
    return guiding_question.strip()


def _parse_task(raw: str, grade: str, topic: str, difficulty: str) -> Task:
    """Extract question and answer from a task JSON response."""
    data = _extract_json(raw)
    question = data.get("question", "")
    answer = data.get("answer", "")
    if not isinstance(question, str) or not question.strip():
        raise RuntimeError(f"Missing or empty 'question' in response: {raw!r}")
    if not isinstance(answer, str) or not answer.strip():
        raise RuntimeError(f"Missing or empty 'answer' in response: {raw!r}")
    return Task(
        task_id=uuid4(),
        question=question.strip(),
        expected_answer=answer.strip(),
        grade=grade,
        topic=topic,
        difficulty=difficulty,
    )


def _parse_hand_slots(raw: str, valid_topics: set[str], hand_size: int) -> list[tuple[str, str]]:
    """Extract (topic, difficulty) pairs from a hand-selector JSON response."""
    valid_difficulties = {"easy", "medium", "hard"}
    data = _extract_json(raw)
    raw_slots = data.get("slots", [])
    if not isinstance(raw_slots, list):
        raise RuntimeError(f"'slots' is not a list in response: {raw!r}")

    slots: list[tuple[str, str]] = []
    for item in raw_slots:
        if not isinstance(item, dict):
            continue
        topic = item.get("topic", "")
        difficulty = str(item.get("difficulty", "")).lower()
        if topic in valid_topics and difficulty in valid_difficulties:
            slots.append((topic, difficulty))
        if len(slots) == hand_size:
            break
    return slots


class LLMProvider(ABC):
    """Abstract interface for an LLM backend."""

    @abstractmethod
    def call(
        self,
        prompt: str,
        system_prompt: str,
        image_png: bytes | None = None,
    ) -> str: ...


class LLMService:
    """Wrapper for the LLMProvider."""

    def __init__(self, provider: LLMProvider) -> None:
        self._provider = provider

    def generate_guidance(
        self,
        question: str,
        context: str,
        image_png: bytes | None = None,
        profile_context: str = "",
        session_id: str | None = None,
    ) -> HelpResponse:
        """Return guiding question generated by the LLM."""
        prompt = build_guide_user_text(question, context, has_image=bool(image_png), profile_context=profile_context)
        ctx = {"session_id": session_id, "call": "generate_guidance"}

        log("llm_request", {**ctx, "question": question, "has_image": image_png is not None})
        try:
            raw = self._provider.call(prompt, GUIDANCE_SYSTEM_PROMPT, image_png)
            guiding_question = _parse_guidance(raw)
        except Exception as exc:
            log("llm_error", {**ctx, "error": str(exc)})
            raise

        return HelpResponse(guiding_question=guiding_question, prompt_used=prompt)

    def generate_tasks(
        self,
        grade: str,
        topic: str,
        difficulty: str,
        count: int,
        curriculum_context: str = "",
        profile_context: str = "",
        session_id: str | None = None,
    ) -> list[Task]:
        """Return list of Task instances generated by the LLM."""
        tasks = []
        for i in range(count):
            prompt = build_task_text(grade, topic, difficulty, curriculum_context, profile_context)
            ctx = {"session_id": session_id, "call": "generate_tasks"}

            log("llm_request", {**ctx, "topic": topic, "difficulty": difficulty, "index": i})
            try:
                raw = self._provider.call(prompt, TASK_SYSTEM_PROMPT)
                task = _parse_task(raw, grade, topic, difficulty)
            except Exception as exc:
                log("llm_error", {**ctx, "error": str(exc)})
                raise

            tasks.append(task)

        return tasks

    def select_hand_slots(
        self,
        topics: list[str],
        profile_context: str,
        hand_size: int,
        session_id: str | None = None,
    ) -> list[tuple[str, str]]:
        """Return (topic, difficulty) pairs for the next hand, chosen by the LLM."""
        prompt = build_hand_selector_text(topics, profile_context, hand_size)
        ctx = {"session_id": session_id, "call": "select_hand_slots"}

        log("llm_request", {**ctx, "hand_size": hand_size})
        try:
            raw = self._provider.call(prompt, HAND_SELECTOR_SYSTEM_PROMPT)
            slots = _parse_hand_slots(raw, set(topics), hand_size)
        except Exception as exc:
            log("llm_error", {**ctx, "error": str(exc)})
            raise

        return slots
